### ISSUE TITLE
derby-render TypeError: Cannot read property 'blockType' of undefined

### ISSUE THREAD

**Issue by same79alal** [psirenny/derby-email#1]
I had derby-email working before.. great project btw! However after doing an update, the derby-render module is broken

TypeError: Cannot read property 'blockType' of undefined
  at Context.child (./node_modules/derby-render/node_modules/derby-templates/lib/contexts.js:79:34)
  at Template.Block.get (./node_modules/derby/node_modules/derby-templates/node_modules/saddle/index.js:633:30)
  at contentHtml (./node_modules/derby/node_modules/derby-templates/node_modules/saddle/index.js:937:24)
  at Template.get (./node_modules/derby/node_modules/derby-templates/node_modules/saddle/index.js:102:10)
  at Template.View.get (./node_modules/derby/node_modules/derby-templates/lib/templates.js:158:19)
  at ./node_modules/derby-render/index.js:22:17
  at ./node_modules/derby-email/lib/index.js:62:18

**Comment by psirenny** [comment]
Thanks. Sorry I took so long to respond to this. I fixed the problem with derby-render so it's working again. I bumped the version to 1.0 and updated the readme with changes. Some of the custom fields have changed and the Body view has been renamed to Html
